	
	/* PAKDD2020 */
	OPTIONS COMPRESS = YES;

	%LET DP = C:\Users\IvanXu\Desktop\data\PAKDD2020;
	LIBNAME ANA "&DP.";
	
	%MACRO GFILE(FN=, DT=,);
		FILENAME &DT. "&DP.\&FN." ENCODING = "UTF-8";
		PROC IMPORT 
			DATAFILE = &DT.
			OUT = &DT. 
			DBMS = CSV 
			REPLACE;
			GETNAMES = YES;
		RUN;
	%MEND;

	%GFILE(FN=disk_sample_fault_tag_all.csv, DT=DT0);
	%GFILE(FN=disk_sample_smart_log_201707.csv, DT=DT1);


	DATA ANA.DT0;
	FORMAT MK $30.;
	SET DT0;
	MK = COMPRESS(SERIAL_NUMBER||MANUFACTURER||MODEL);
	DROP SERIAL_NUMBER MANUFACTURER MODEL;
	RUN;

	DATA ANA.DT1;
	FORMAT MK $30. FDT YYMMDD10.;
	SET DT1;
	MK = COMPRESS(SERIAL_NUMBER||MANUFACTURER||MODEL);
	FDT = INPUT(COMPRESS(DT), YYMMDD8.);
	DROP SERIAL_NUMBER MANUFACTURER MODEL _;
	RUN;

	/*
		MK DIFF TAG IN ONE FAULT_TIME DAY.
	*/
	PROC SQL;
	CREATE TABLE ANA.DT0_SUM AS
	SELECT
		MK,
		FAULT_TIME,
		1 AS TAG,
		MAX(CASE WHEN TAG = 0 THEN 1 ELSE 0 END) AS TAG0,
		MAX(CASE WHEN TAG = 1 THEN 1 ELSE 0 END) AS TAG1,
		MAX(CASE WHEN TAG = 2 THEN 1 ELSE 0 END) AS TAG2,
		MAX(CASE WHEN TAG = 3 THEN 1 ELSE 0 END) AS TAG3,
		MAX(CASE WHEN TAG = 4 THEN 1 ELSE 0 END) AS TAG4,
		MAX(CASE WHEN TAG = 5 THEN 1 ELSE 0 END) AS TAG5,
		MAX(CASE WHEN TAG = 6 THEN 1 ELSE 0 END) AS TAG6
	FROM ANA.DT0
	GROUP BY MK, FAULT_TIME;
	QUIT;

	%MACRO R();
		DATA ANA.DT1_SUM;
		SET ANA.DT1;
		%DO I = 1 %TO 255;
			_SMART_&I._NORMALIZED = INT(SMART_&I._NORMALIZED);
			_SMART_&I.RAW = INT(SMART_&I.RAW);

			DROP SMART_&I._NORMALIZED SMART_&I.RAW;
		%END;
		RUN;	

		PROC SQL;
		CREATE TABLE ANA.DT1_SUM(DROP = _T) AS
		SELECT
			MK,
			FDT,
			SUM(1) AS CNT,
			%DO I = 1 %TO 255;
				/* SMART_1_NORMALIZED, SMART_1RAW */
				MIN(_SMART_&I._NORMALIZED)	AS SMART_&I._NORMALIZED_MIN,
				MEAN(_SMART_&I._NORMALIZED)	AS SMART_&I._NORMALIZED_AVG,
				MAX(_SMART_&I._NORMALIZED)	AS SMART_&I._NORMALIZED_MAX,
				
				MIN(_SMART_&I.RAW) 	AS SMART_&I.RAW_MIN,
				MEAN(_SMART_&I.RAW) AS SMART_&I.RAW_AVG,
				MAX(_SMART_&I.RAW)	AS SMART_&I.RAW_MAX,
				
			%END;
			1 AS _T
		FROM ANA.DT1_SUM
		GROUP BY MK, FDT;
		QUIT;
	%MEND R;
	%R();


/*	DATA ANA.DT10;*/
/*	MERGE ANA.DT1_SUM(IN = A) ANA.DT0_SUM(IN = B);*/
/*	BY MK;*/
/*	IF A;*/
/*	RUN;*/
/**/
/*	DATA ANA.DT10L;*/
/*	SET ANA.DT10;*/
/*	IF FAULT_TIME - FDT = 30;*/
/*	KEEP MK;*/
/*	RUN;*/
/*	PROC SORT DATA = ANA.DT10L NODUPKEY;*/
/*	BY MK;*/
/*	RUN;*/
/**/
/*	DATA ANA.DT10L_B;*/
/*	FORMAT MK FDT FAULT_TIME D_FDT I_FDT TAG: CNT;*/
/*	MERGE ANA.DT10(IN = A) ANA.DT10L(IN = B);*/
/*	BY MK;*/
/*	IF A AND B;*/
/*	D_FDT = FAULT_TIME - FDT;*/
/*	I_FDT = D_FDT = 30;*/
/*	RUN;*/



