data_dir: 'data/CMeIE/json/'
dev_data: 'data/CMeIE/json/dev.json'
test_data: 'data/CMeIE/json/test.json'
train_data: 'data/CMeIE/json/train.json'
task: 'cmeie'
entity_model: 'bert-base-chinese'
entity_do_train: True
entity_do_eval: True
entity_eval_test: True
entity_single_card: False
entity_learning_rate: 1e-05
entity_task_learning_rate: 5e-04
entity_train_batch_size: 64
entity_num_epoch: 60
entity_context_window: 300
entity_output_dir: 'pretrain_models/ent-cmeie-ctx0/'
entity_test_pred_filename: 'ent_pred_test.json'
entity_dev_pred_filename: 'ent_pred_dev.json'
entity_eval_batch_size: 32
entity_eval_per_epoch: 1
entity_bert_model_dir: 
entity_bertadam: False
entity_max_span_length: 8
entity_print_loss_step: 100
entity_seed: 0
entity_train_shuffle: False
entity_use_albert: False
entity_warmup_proportion: 0.1

eval_metric: 'f1'
no_cuda: False
relation_model: 'bert-base-chinese'
relation_train_file: 'data/CMeIE/json/train.json'
relation_do_train: True 
relation_do_eval: True
relation_eval_test: True
relation_do_lower_case: True
relation_single_card: False
relation_train_batch_size: 64
relation_eval_batch_size: 64
relation_learning_rate: 2e-5
relation_num_train_epochs: 3
relation_context_window: 0
relation_max_seq_length: 128
relation_output_dir: 'pretrain_models/rel-cmeie-ctx0/'
relation_entity_predictions_dev: 'ent_pred_dev.json'
relation_entity_predictions_test: 'ent_pred_test.json'
relation_add_new_tokens: False
relation_bertadam: False
relation_eval_per_epoch: 5
relation_eval_with_gold: False
relation_negative_label: 'no_relation'
relation_prediction_file: 'predictions.json'
relation_seed: 0
relation_train_mode: 'random_sorted'
relation_warmup_proportion: 0.1
