clip_grad: 2.
corpus_type: 'WebNLG'
corres_threshold: 0.5
data_cache: False
device_id: 0
downs_en_lr: 1e-3
drop_prob: 0.3  
emb_fusion: 'concat'
ensure_corres: True
ensure_rel: True
epoch_num: 5
ex_index: 3
fin_tuning_lr: 1e-4
gradient_accumulation_steps: 2
max_seq_length: 100
min_epoch_num: 5
mode: 'test'
multi_gpu: False
num_negs: 4
patience_num: 20
patience: 0.00001
pretrain_model: 'bert_base_cased'
rel_threshold: 0.1
restore_file: ''
seed: 2020
test_batch_size: 64
train_batch_size: 16
val_batch_size: 24
warmup_prop: 0.1
weight_decay_rate: 0.01