# ??? is a mandatory value.
# you should be able to set it without open_dict
# but if you try to read it before it's set an error will get thrown.

# populated at runtime
cwd: ???


defaults:
  - hydra/output: custom
  - preprocess
  - train
  - embedding
  - predict
  - model: cnn   # [cnn, rnn, transformer, capsule, gcn, lm]


