# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_kfbReader', [dirname(__file__)])
        except ImportError:
            import _kfbReader
            return _kfbReader
        if fp is not None:
            try:
                _mod = imp.load_module('_kfbReader', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _kfbReader = swig_import_helper()
    del swig_import_helper
else:
    import _kfbReader
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class reader(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, reader, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, reader, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _kfbReader.new_reader()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _kfbReader.delete_reader
    __del__ = lambda self: None

    def ReadInfo(self, kfbPath, scale=0, readAll=False):
        return _kfbReader.reader_ReadInfo(self, kfbPath, scale, readAll)

    def ReadRoi(self, x, y, w, h, scale):
        arr = _kfbReader.reader_ReadRoi(self, x, y, w, h, scale)
        arr = arr.reshape([h, w, 3])
        return arr


    def ReadPreview(self):
        return _kfbReader.reader_ReadPreview(self)

    def getWidth(self):
        return _kfbReader.reader_getWidth(self)

    def getHeight(self):
        return _kfbReader.reader_getHeight(self)

    def getReadScale(self):
        return _kfbReader.reader_getReadScale(self)

    def setReadScale(self, scale):
        return _kfbReader.reader_setReadScale(self, scale)

    def readLabelImage(self):
        return _kfbReader.reader_readLabelImage(self)
reader_swigregister = _kfbReader.reader_swigregister
reader_swigregister(reader)

# This file is compatible with both classic and new-style classes.


