cwd: ???

seed: 1

bart_name: "facebook/bart-large"
dataset_name: conll2003
device: cuda

num_epochs: 30
batch_size: 16
learning_rate: 2e-5
warmup_ratio: 0.01
eval_begin_epoch: 16
src_seq_ratio: 0.6
tgt_max_len: 10
num_beams: 1
length_penalty: 1

use_prompt: True
prompt_len: 10
prompt_dim: 800

freeze_plm: True
learn_weights: True
notes: ''
save_path: null # 模型保存路径
load_path: load_path # 模型加载路径，不能为空
write_path: "data/conll2003/predict.txt"