seed: 1

use_gpu: True
gpu_id: 0

epoch: 50
batch_size: 32
learning_rate: 3e-4
lr_factor: 0.7 # 学习率的衰减率
lr_patience: 3 # 学习率衰减的等待epoch
weight_decay: 1e-3 # L2正则

early_stopping_patience: 6

train_log: True
log_interval: 10
show_plot: True
only_comparison_plot: False
plot_utils: matplot  # [matplot, tensorboard]

predict_plot: False